M48
; DRILL file {KiCad 7.0.2} date Mon May 22 10:47:59 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-22T10:47:59+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.100
%
G90
G05
T1
X91.2Y-84.25
X100.5Y-85.425
T2
X82.0Y-74.46
X82.0Y-77.0
X82.0Y-80.96
X82.0Y-83.5
X82.0Y-87.46
X82.0Y-90.0
T3
X110.0Y-80.96
X110.0Y-83.5
T0
M30
