M48
; DRILL file {KiCad 7.0.2} date Tue Dec 12 16:53:09 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-12T16:53:09+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X124.95Y-80.4
X124.95Y-84.0
X124.95Y-87.6
T2
X99.0Y-84.0
X139.0Y-84.0
T0
M30
