M48
; DRILL file {KiCad 7.0.2} date Mon May 22 10:47:59 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-22T10:47:59+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X112.54Y-80.96
X112.54Y-83.5
T2
X111.0Y-75.0
X111.0Y-89.0
T0
M30
